name: "🛠️ Project Proposal"
description: "Submit a detailed proposal for a new project."
title: "🛠️ Project Proposal: "
labels: [proposal]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a new project request! 🙏 Please fill out the form below with all the relevant details to help us evaluate your proposal.
  - type: textarea
    id: project-description
    validations:
      required: true
    attributes:
      label: "🔖 Project Description"
      description: "Provide a clear, concise description of the project, including its purpose and key features."
      placeholder: "The project aims to ..."
  - type: textarea
    id: pitch
    validations:
      required: true
    attributes:
      label: "🎤 Project Pitch"
      description: "Explain why this project should be added and how it aligns with our goals. Outline the implementation plan briefly."
      placeholder: "This project should be added because ..."
  - type: textarea
    id: expected-outcome
    validations:
      required: true
    attributes:
      label: "📈 Expected Outcome"
      description: "Describe the expected results or benefits of implementing this project."
      placeholder: "The expected outcome is ..."
  - type: textarea
    id: screenshots
    attributes:
      label: "📷 Screenshots"
      description: "Attach screenshots or design mockups, if applicable."
      placeholder: "Include relevant visuals here."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "✔️ Checklist"
      options:
        - label: "I have checked and confirmed no similar projects exist."
          required: true
        - label: "I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I am a Hacktoberfest 2024 contributor."
          required: false
        - label: "I am willing to work on this issue."
          required: false
  - type: textarea
    id: additional-notes
    attributes:
      label: "📝 Additional Notes (Optional)"
      description: "Include any other relevant information or notes about the project."
      placeholder: "Any additional details..."
    validations:
      required: false
